### ISSUE TITLE
Error in canvas_mesh() : could not find function "canvas_mesh"

### ISSUE THREAD

**Issue by JanBren** [koenderks/aRtsy#160]
**Describe the bug**
The following function is not working: canvas_mesh()
Error displayed: Error in canvas_mesh() : could not find function "canvas_mesh"
Thanks

**Comment by koenderks** [comment]
Did you use `library(aRtsy)` before calling `canvas_mesh()`? It cannot reproduce this with the latest package from CRAN.

**Comment by koenderks** [comment]
Any luck with this? If this has worked, you can close this issue.
