### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by krzbanas** [koenderks/aRtsy#162]
**Describe the bug**
First, I would like to thank you for this package. It has great educational value for me. 
I noticed recently that it looks that function canvas_smoke() is not loading with library(aRtsy) command

**To Reproduce**
```
library(aRtsy)
canvas_smoke(colors = colorPalette("random", 1024))
```

>  Error in canvas_smoke(colors = colorPalette("random", 1024)) : 
>  could not find function "canvas_smoke"

**Expected behavior**
output plot from canvas_smoke 

**Screenshots**

**Desktop (please complete the following information):**
`packageVersion("aRtsy")`

>   ‘0.2.1’

`sessionInfo()`

>  R version 4.2.2 (2022-10-31)
>  Platform: aarch64-apple-darwin20 (64-bit)
>  Running under: macOS Ventura 13.2.1

**Additional context**

`lsf.str("package:aRtsy") `

>  canvas_ant : function (colors, background = "#fafafa", iterations = 1e+06, resolution = 500)  
>  canvas_blacklight : function (colors, n = 1000, resolution = 500)  
>  canvas_chladni : function (colors, waves = 5, warp = 0, resolution = 500, angles = NULL, distances = NULL)  
>  canvas_circlemap : function (colors, left = 0, right = 12.56, bottom = 0, top = 1, iterations = 10, resolution = 1500)  
>  canvas_cobweb : function (colors, background = "#fafafa", lines = 300, iterations = 100)  
>  canvas_collatz : function (colors, background = "#fafafa", n = 200, angle.even = 0.0075, angle.odd = 0.0145, side = FALSE)  
>  canvas_diamonds : function (colors, background = "#fafafa", col.line = "black", radius = 10, alpha = 1, p = 0.2, resolution = 500)  
>  canvas_flame : function (colors, background = "#000000", iterations = 1e+06, variations = 0, symmetry = 0, blend = TRUE, weighted = FALSE, 
>                                        post = FALSE, final = FALSE, extra = FALSE, display = c("colored", "logdensity"), zoom = 1, resolution = 1000, 
>                                        gamma = 1)  
>  canvas_flow : function (colors, background = "#fafafa", lines = 500, lwd = 0.05, iterations = 100, stepmax = 0.01, polar = FALSE, 
>                                         angles = NULL)  
>  canvas_forest : function (colors, n = 1000, resolution = 500)  
>  canvas_function : function (colors, background = "#fafafa", by = 0.01, polar = TRUE, formula = NULL)  
>  canvas_gemstone : function (colors, n = 1000, resolution = 500)  
>  canvas_mandelbrot : function (colors, iterations = 100, zoom = 1, left = -1.7, right = -0.2, bottom = -0.2999, top = 0.8001, resolution = 500)  
>  canvas_maze : function (color = "#fafafa", walls = "black", background = "#fafafa", resolution = 20, polar = FALSE)  
>  canvas_mesh : function (colors, background = "#fafafa", transform = c("perlin", "fbm", "simplex", "cubic", "worley", "knn", "rf", 
>                                        "svm"), lines = 500, iterations = 500, mixprob = 0)  
>  canvas_mosaic : function (colors, n = 1000, resolution = 500)  
>  canvas_nebula : function (colors, k = 50, n = 500, resolution = 500)  
>  canvas_petri : function (colors, background = "#fafafa", dish = "black", attractors = 1000, iterations = 15, hole = 0) 
>  canvas_phyllotaxis : function (colors, background = "#fafafa", iterations = 10000, angle = 137.5, size = 0.01, alpha = 1, p = 0.5)  
>  canvas_planet : function (colors, threshold = 4, iterations = 200, starprob = 0.01, fade = 0.2, radius = NULL, center.x = NULL, 
>                                         center.y = NULL, light.right = TRUE, resolution = 1500)  
>  canvas_polylines : function (colors, background = "#fafafa", ratio = 0.5, iterations = 1000, size = 0.1, resolution = 500)  
>  canvas_recaman : function (colors, background = "#fafafa", iterations = 100, start = 0, increment = 1, curvature = 1, angle = 0, 
>                                          size = 0.1, closed = FALSE)  
>  canvas_ribbons : function (colors, background = "#fdf5e6", triangle = TRUE)  
>  canvas_segments : function (colors, background = "#fafafa", n = 250, p = 0.5, H = 0.1, size = 0.2)  
>  canvas_splits : function (colors, background = "#fafafa", iterations = 6, sd = 0.2, lwd = 0.05, alpha = 0.5)  
>  canvas_squares : function (colors, background = "#000000", cuts = 50, ratio = 1.618, resolution = 200, noise = FALSE)  
>  canvas_stripes : function (colors, n = 300, H = 1, burnin = 1)  
>  canvas_strokes : function (colors, neighbors = 1, p = 0.01, iterations = 1, resolution = 500, side = FALSE)  
>  canvas_turmite : function (colors, background = "#fafafa", p = 0, iterations = 1e+06, resolution = 500, noise = FALSE)  
>  canvas_watercolors : function (colors, background = "#fafafa", layers = 50, depth = 2, resolution = 250)  
>  colorPalette : function (name, n = NULL)  
>  saveCanvas : function (plot, filename, width = 7, height = 7, dpi = 300)  
>  theme_canvas : function (x, background = NULL, margin = 0)

**Comment by koenderks** [comment]
Thanks! The latest version (that includes the canvas_smoke function) of aRtsy is not available on CRAN yet, but if you download the development version from GitHub then you can access the function. I will do my best to send the version that includes this function to CRAN soon!

**Comment by koenderks** [comment]
The package is now on cran.
